### ISSUE TITLE
Events not received by AVD client

### ISSUE THREAD

**Issue by halstjas** [jordanbyron/react-native-event-source#13]
I would like to utilise this library within my project but despite seeing the subscription within my server.   no events are being received the addEventListner please see my code snippet below:
Any assistance greatly appreciated.

import RNEventSource from 'react-native-event-source'

class ChatForm extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            login : this.props.user.login,
            password : this.props.user.password,
            role: this.props.user.role,
            group : this.props.user.group,
            chatPostUrl : server + 'chatSend',
            chatStreamUrl : server + 'chatStream',
            messages: []
        }

        this.processEvent = this.processEvent.bind(this);        
    }

    componentDidMount() {
        const { login, group, password, role, chatStreamUrl } = this.state
        
        const version = new Date();
        let chatUrl = chatStreamUrl;
        chatUrl += '?group=' + group;
        chatUrl += '&login=' + login;
        chatUrl += '&password=' + password;
        chatUrl += '&role=' + role;
        chatUrl += '&version=' + version;

        const eventSource = new RNEventSource(chatUrl);
        eventSource.addEventListner = this.processEvent;
    }

    processEvent (event) {
        alert("Message received")
        const { login } = this.state;
        //alert(event);
        const msg = event.data;
        alert(msg);
        const message = JSON.parse(msg);

        const chatMessage = [
            {
                _id: message._id,
                text: message.msg, 
                createdAt: message.Date,
                user: {
                    _id: message.loginID,
                    name: message.login
                }
            }
        ]

        if ( login !== message.login ) {
            this.setState(previousState => ({
                messages: GiftedChat.append(previousState.messages, chatMessage)
            }))
        }
    }

**Comment by jordanbyron** [comment]
This is a question better suited for StackOverflow rather than our bug tracker, as it is not a defect in `react-native-event-store`. Best of luck!
