### ISSUE TITLE
No event logged on Expo

### ISSUE THREAD

**Issue by ceessay** [jordanbyron/react-native-event-source#23]
I am using this library. But I cannot make it work. My logs won't print anything. I am supposed to get data from my server every 10 seconds. Maybe I am missing something. Here is a snippet.
Post on SO: https://stackoverflow.com/questions/56654542/how-to-listen-to-server-side-events-in-react-native

```
//.... imports here
  getTodayMissions() {
    const { userStore } = this.props;
    const user = toJS(userStore.user);
    const BASE_URL = env.apiUrl;
    const eventsurl = `${BASE_URL}/server-events/`;
    const eventSource = new RNEventSource(eventsurl);
    const url = `missionstodayapp?userId=${user.id}`;

    console.log('start the watch', eventsurl, url);
    this.eventSource.addEventListener(url, (data) => {
      console.log('started the watch', data);
    });
  }
```

**Comment by jordanbyron** [comment]
Hi @ceessay! This is a question better suited for StackOverflow rather than our bug tracker, as it is not obviously a defect in `react-native-event-store`. If you find there is a bug in our package please feel free to open a new issue with steps to reproduce. Best of luck!
