### ISSUE TITLE
Why connection closes and re-opens automatically ?

### ISSUE THREAD

**Issue by ghasemikasra39** [jordanbyron/react-native-event-source#25]
After some minutes, I have noticed that the keep-alive connection automatically closes and re-opens itself. Additionally, when I decrease the interval, with which the data is sent over the connection, the close/re-open behaviour interval increases (closes/re-opens happens faster).

Is this a predefined behaviour ? Or a bug?

**Comment by jordanbyron** [comment]
That is known behavior, defined here:

https://github.com/jordanbyron/react-native-event-source/blob/master/EventSource.js#L55-L58

Added in v1.0.3 as a configurable option:

https://github.com/jordanbyron/react-native-event-source/releases/tag/v1.0.3
