### ISSUE TITLE
body is undefined 

### ISSUE THREAD

**Issue by ghasemikasra39** [jordanbyron/react-native-event-source#26]
```javascript
// Client : React Native App
const options = {body: {unitId: 'some id'}, headers: {Authorization: 'some token'}};
this.eventSource = new RNEventSource('http://ip:port/eventstream', options); 
this.eventSource.addEventListener('message', (payload) => console.log(payload));
```
```javascript
// Server : NodeJS App
router.get('/eventstream', (req, res, next) => {
    console.log(req.body); // --> undefined 
})
```

I am using `Express.js` with `body-parser`.

**Comment by Arminhosseini** [comment]
I also got this issue.

**Comment by aliassarpro** [comment]
It happened for me to. Can you fix it pls?

**Comment by arnaudambro** [comment]
same for me

**Comment by jordanbyron** [comment]
Hey ya'll!

It looks like your express server is assuming the client will send something in the request body, but I'm not sure that is the case. Server-sent events, by definition, is the idea of sending data from the server (express in this case) to the client (react-native). It might be helpful to learn a bit more about how that works and give this library another shot. I did a quick internet search and found this article which may be helpful:

https://tomkersten.com/articles/server-sent-events-with-node/

In the meantime if you find a bug with this library please don't hesitate to open up a new ticket with steps to reproduce and I'll take a look.
