### ISSUE TITLE
App stops receiving events after refreshing simulator

### ISSUE THREAD

**Issue by kyle-ssg** [jordanbyron/react-native-event-source#3]
For some reason I have to keep restarting the app from xcode in order for events to be triggered.

**Comment by kyle-ssg** [comment]
Also, looking at the onMessage callback in RNEventSource.m does the following not make more sense -


    [self.eventSource onMessage: ^(Event *e) {
        RCTLogInfo(@"EventSource");
        if (e.event) {
            [self.bridge.eventDispatcher sendDeviceEventWithName:e.event

e.event contains the actual event name that was sent, therefore you can easily replicate the js implementation of EventSource e.g.


window.EventSource = function(url) {
    var src = require('NativeModules').RNEventSource;
    src.connectWithURL(url);
    return  {
        addEventListener: function(name, cb) {
            DeviceEventEmitter.addListener(name, cb);
        }
    }
}

**Comment by jordanbyron** [comment]
> For some reason I have to keep restarting the app from xcode in order for events to be triggered.

That's strange. I am not having those issues. Are you seeing the EventSource log messages in your XCode console? Can you show me your code?

> Also, looking at the onMessage callback in RNEventSource.m does the following not make more sense ....

I see what you are saying here. `onMessage` is actually working the way it should (Sending all message events from the server) but you want to also expose [EventSource](https://github.com/neilco/EventSource#client-code)'s `addEventListener` method. What you have written is pretty close to what I'd imagine `addEventListener` would look like, except that I'd want to scope the `sendDeviceEventWithName` name to something like `EventSource:<EVENT_NAME>` that way we don't have to worry about stepping on any other device events. Does that make sense? Do you think that's something you could handle implementing?

**Comment by JonnyBGod** [comment]
Having a similar problem.

RN 0.13.1
xcode7 output: 
```
2015-10-26 17:53:13.657 [info][tid:main][RNEventSource.m:43] EventSource: Error (null): (null)
2015-10-26 17:53:14.185 [info][tid:main][RNEventSource.m:43] EventSource: Error (null): (null)
2015-10-26 17:53:14.753 [info][tid:main][RNEventSource.m:43] EventSource: Error (null): (null)
2015-10-26 17:53:14.754 [info][tid:main][RNEventSource.m:43] EventSource: Error (null): (null)
2015-10-26 17:53:15.276 [info][tid:main][RNEventSource.m:43] EventSource: Error (null): (null)
```

Also persists after refreshing app. Need to fully restart app to stop getting errors.

**Comment by JonnyBGod** [comment]
I found about what was causing the error (my side), but the EventSource keeps running even after `EventSource.close();` is called.

**Comment by jordanbyron** [comment]
@JonnyBGod @kyle-ssg the latest version just pushed should address the multiple connection problem you were seeing after refreshing. I also exposed detailed error messages to the `onError` listener to help debug problematic connections.
