### ISSUE TITLE
Connection closing after a few seconds

### ISSUE THREAD

**Issue by JonnyBGod** [jordanbyron/react-native-event-source#4]
For some reason the connection is closing after a few seconds with following log:

```
RNEventSource: onError (Error Domain= Code=2 "Connection with the event source was closed." UserInfo={NSLocalizedDescription=Connection with the event source was closed.})

Object {code: 2, description: "Connection with the event source was closed.", domain: ""}

RNEventSource: Closed
```

I have double checked if this could be a server related problem but I am using EventSource from a web client with no problems what so ever.

Any idea what might be causing this issue?

**Comment by jordanbyron** [comment]
@JonnyBGod can you share your source code? Without more context I won't be able to help figure out what's going on.

**Comment by JonnyBGod** [comment]
```
let EventSource = require('NativeModules').RNEventSource;

class SomeComponent = React.createClass({
  getInitialState() {
    return {
      url: api.API_URL +'/rides/change-stream?_format=event-source&access_token='+ api.credentials.accessTokenId,
    };
  },

  componentDidMount() {
    this.subscription = {
      message: React.DeviceEventEmitter.addListener(
        'EventSourceMessage', function(change) {
          console.log(change);
        }.bind(this)),

      connected: React.DeviceEventEmitter.addListener(
        'EventSourceConnected', function(message) {
          console.log(message);
        }),

      err: React.DeviceEventEmitter.addListener(
        'EventSourceError', function(error) {
          console.log(error);
        })
    };

    EventSource.connectWithURL(this.state.url);
  },

  componentWillUnmount() {
    EventSource.close();
    this.subscription.message.remove();
    this.subscription.connected.remove();
    this.subscription.err.remove();
  }
...
});
```

**Comment by JonnyBGod** [comment]
Thing is that the connection works for irregular periods, from a few seconds to about a minute.

Also tested to check if this was some kind of time out, but it does not seam so as this happens with or with out events coming through...

**Comment by jordanbyron** [comment]
Try pointing your code to `http://samshull.com/server-sent/events.php` and see if the error persists.

**Comment by JonnyBGod** [comment]
Same issue with your endpoint:

```
2015-12-11 18:39:00.544 [info][tid:main][RNEventSource.m:40] RNEventSource: onOpen
2015-12-11 18:39:00.547 [info][tid:main][RNEventSource.m:60] RNEventSource: onMessage ((null): (null))
2015-12-11 18:39:00.547 [info][tid:com.facebook.React.JavaScript] { data: null, event: 'connected' }
2015-12-11 18:40:00.456 [info][tid:main][RNEventSource.m:48] RNEventSource: onError (Error Domain= Code=2 "Connection with the event source was closed." UserInfo={NSLocalizedDescription=Connection with the event source was closed.})
2015-12-11 18:40:00.457 [info][tid:main][RNEventSource.m:71] RNEventSource: Closed
2015-12-11 18:40:00.460 [error][tid:com.facebook.React.JavaScript] { description: 'Connection with the event source was closed.',
  code: 2,
  domain: '' }
```

**Comment by JonnyBGod** [comment]
It seems to happen about 1 minute after connection in most cases when no events are triggered.

**Comment by JonnyBGod** [comment]
Also worth to mention that I use more than one EventStream at a time.

**Comment by jordanbyron** [comment]
Does it work when you use just one connection?
On Fri, Dec 11, 2015 at 1:47 PM João Ribeiro <notifications@github.com>
wrote:

> Also worth to mention that I use more than one EventStream at a time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jordanbyron/react-native-event-source/issues/4#issuecomment-164015385>
> .
>
-- 
Jordan

**Comment by JonnyBGod** [comment]
Sorry updated last comment. But no, still same problem with just one EventSource.

After closer inspection I now realize that this should be related to timeout. The connection apparently closes exactly one minute after last event.

Are you sending some kind of ping to maintain the connection live?

**Comment by jordanbyron** [comment]
Your SSE server should be pinging the client, not the other way around.

**Comment by jordanbyron** [comment]
See [this implementation](https://github.com/jordanbyron/alarm_keypad/blob/master/stream.rb#L30) for an example. The server sends periodic `keepalive` messages to the client and removes them from the connection if they disappear. It also times clients out after 10 pings.

**Comment by JonnyBGod** [comment]
Ok. Will try to fix that. But apparently no real problem from this library related to this issue. Thanks for you help.

**Comment by jordanbyron** [comment]
No problem. Best of luck!

**Comment by mythz** [comment]
I'm also getting hit with the EventSource closing as soon as my client sends a periodic heartbeat to the server. If I delay the heartbeat, it delays the closing of the EventSource connection.

Do you know if this is implicit behavior in XHR where it will terminate any existing connections to the same domain? and do you know if this behavior is configurable in React Native?

**Comment by rigbot01** [comment]
Facing the same problem. The connection keeps getting dropped every 30-40 seconds despite the SSE server is sending keep alive messages to the client. But when it is connected, the client is receiving both keep alive and actual data messages. When the connection is dropped, the connection is reestablished but it gets dropped again and this cycle repeats. Any idea what might be causing this issue?

**Comment by jordanbyron** [comment]
@rigbot01 no clue. It would help if you could provide a bare minimum example app that demonstrates the problem you are describing. If you can do that please open up a new ticket and reference this one.
